---
# deployment profiles are intended to provide good defaults for a given deployment topology
# (default, remote, ambient, etc).
#profile: demo

global:
  logging:
    # set the default log level for all control plane components.
    # expected values are: debug|info|warn|error|critical|none
    level: "debug"
    # to specify log levels for individual scopes (e.g., "default:warn,ads:error"), use componentLogLevel.
    #componentLogLevel: ""

  # platform profiles are intended to provide necessary platform-specific defaults,
  # for a given target platform (eks, gke, openshift, etc).
  #platform: eks

