---
apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://gateway:3100
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
  secureJsonData:
    httpHeaderValue1: "tenant1"
- name: Mimir
  type: prometheus
  access: proxy
  orgId: 1
  url: http://gateway:3100/prometheus
  version: 1
  editable: true
  isDefault: true
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
    alertmanagerUid: "alertmanager"
  secureJsonData:
    httpHeaderValue1: "tenant1"
- name: Mimir Alertmanager
  type: alertmanager
  uid: alertmanager
  access: proxy
  orgId: 1
  url: http://gateway:3100
  version: 1
  editable: true
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
    implementation: "cortex"
  secureJsonData:
    httpHeaderValue1: "tenant1"
