---
apiVersion: 1
datasources:
- name: alertmanager
  type: alertmanager
  uid: alertmanager
  access: proxy
  orgId: 1
  url: "http://gateway:3100"
  version: 1
  editable: true
  isDefault: false
  basicAuth: false
  jsonData:
    implementation: "cortex"
    httpHeaderName1: "X-Scope-OrgID"
  secureJsonData:
    httpHeaderValue1: "tenant1"
- name: loki
  type: loki
  uid: loki
  access: proxy
  url: "http://gateway:3100"
  orgId: 1
  version: 1
  editable: true
  isDefault: false
  basicAuth: false
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
  secureJsonData:
    httpHeaderValue1: "tenant1"
- name: mimir
  type: prometheus
  uid: mimir
  access: proxy
  url: "http://gateway:3100/prometheus"
  orgId: 1
  version: 1
  editable: true
  isDefault: true
  basicAuth: false
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
  secureJsonData:
    httpHeaderValue1: "tenant1"
- name: tempo
  type: tempo
  uid: tempo
  access: proxy
  url: "http://tempo:3200"
  orgId: 1
  version: 1
  editable: true
  isDefault: false
  basicAuth: false
  apiVersion: 1
  jsonData:
    httpHeaderName1: "X-Scope-OrgID"
    serviceMap:
      datasourceUid: mimir
  secureJsonData:
    httpHeaderValue1: "tenant1"
