---
nginx:
  enabled: false

gateway:
  enabledNonEnterprise: true
  nginx:
    basicAuth:
      enabled: true
      existingSecret: basic-auth

#  ingress:
#    enabled: true
#    hosts:
#      - host: mimir.local
#        paths:
#          - path: /
#            pathType: Prefix

minio:
  enabled: true

query_frontend:
  replicas: 1

query_scheduler:
  replicas: 1

querier:
  replicas: 1

distributor:
  replicas: 1

ingester:
  replicas: 3
  zoneAwareReplication:
    enabled: false

store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
