---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: webapp
  name: webapp-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: webapp-vaultauth
  namespace: webapp
spec:
  method: kubernetes
  mount: demo-kube
  kubernetes:
    role: app-role1
    serviceAccount: webapp-manager
    audiences:
      - vault

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webapp-vaultkv
  namespace: webapp
spec:
  type: kv-v2
  mount: kvv2
  path: webapp/config
  vaultAuthRef: webapp-vaultauth

  # dest k8s secret
  destination:
    name: webapp-vaultsync
    create: true
  refreshAfter: 30s

