#!/bin/bash

set -e
declare -a HELM_ARGS

VERSION=1.0.0

version() {
    echo "Version: $VERSION"
    exit 1
}

usage() {
    echo "Usage: $0 [deploy|diff|uninstall|version] <path to YAML config file>"
    exit 1
}

eval_kube () {
    # Check if 'kubectl' is installed
    if ! command -v kubectl &> /dev/null; then
        echo "Error: kubectl is not installed or not in PATH. Please install it and ensure it is accessible." >&2
        exit 1
    fi

    # Check if 'Kubernetes cluster' is running
    if ! kubectl cluster-info &> /dev/null; then
        echo "Error: Kubernetes cluster is not running or not accessible." >&2
        exit 1
    else
        echo "✓ Kubernetes cluster is running."
	kubectl cluster-info | head -n 1
        echo "" # new line
    fi
}

prep_req () {
    local tool_conf=".helmctl.conf"

    # Check if 'helm' is installed
    if ! command -v helm &> /dev/null; then
        echo "Error: helm is not installed or not in PATH. Please install it and ensure it is accessible." >&2
        exit 1
    else
        echo "✓ helm $(helm version --short) found."
    fi

    # Check if helm 'diff' plugin is installed
    if ! helm plugin list | grep -q "diff"; then
        echo "Error: helm 'diff' plugin not found. Installing now..."
        helm plugin install "https://github.com/databus23/helm-diff"
        echo "✓ helm diff plugin $(helm diff version) is installed."
    else
        echo "✓ helm diff plugin $(helm diff version) found."
    fi

    # Check if 'yq' is installed
    if ! command -v yq &> /dev/null; then
        echo "Error: yq is not installed. Please install it to proceed." >&2
        exit 1
    else
        echo "✓ $(yq --version) found."
        echo "" # new line
    fi

    eval_kube
}

load_config () {
    local script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
    local helm_conf=""

    # traverse all params to find a config (yaml|yml) file
    # if found, exit the loop
    for arg in "$@"; do
        if [[ "$arg" == *.yaml || "$arg" == *.yml ]]; then
            helm_conf="$arg"
            break 
        fi
    done

    # verify the config file
    if [[ -z "$helm_conf" ]]; then
        echo "Error: No .yaml or .yml file is provided."
        usage
        exit 1
    elif [[ ! -f "$helm_conf" ]]; then
        echo "Error: Configuration file '$helm_conf' does not exist."
        exit 1
    fi

    # Load parameters from YAML file
    HELM_ARGS+=($(yq e '.release' "$helm_conf"))
    HELM_ARGS+=($(yq e '.chart' "$helm_conf"))
    HELM_ARGS+=(--version $(yq e '.version' "$helm_conf"))
    HELM_ARGS+=(--namespace $(yq e '.namespace' "$helm_conf"))

    while IFS= read -r val_file; do
        if [ -n "$val_file" ]; then
            HELM_ARGS+=(--values "$val_file")
        fi
    done < <(yq e '.values[]?' "$helm_conf")

    kube_ctx=$(yq e '.context' "$helm_conf")
    if [ -n "$kube_ctx" ] && [ "$kube_ctx" != "null" ]; then
        HELM_ARGS+=(--kube-context "$kube_ctx")
    fi
}

deploy() {
    read -p "✓ Do you want to deploy '${HELM_ARGS[0]}'? [y/n]: " choice
    case $choice in
        yes|y)
            echo "Deploy: ${HELM_ARGS[0]}"
            helm upgrade --install "${HELM_ARGS[@]}" \
                --create-namespace
            ;;
        *) echo "✓ Cancelled by user."
            exit 1
            ;;
    esac
}

diff() {
    # Check if the captured variable is NOT an empty string
    found_release=$(helm list -f "^${HELM_ARGS[0]}$" -q -A --deployed 2>/dev/null)

    if [ -n "$found_release" ]; then
        # Release found (string is not empty)
        echo "Preview changes: ${HELM_ARGS[0]}"
        helm diff upgrade "${HELM_ARGS[@]}" \
            --context 4 --three-way-merge
    else
        echo "Error: '${HELM_ARGS[0]}' not found"
    fi
}

uninstall() {
    read -p "✓ Do you want to uninstall '${HELM_ARGS[0]}'? [y/n]: " choice
    case $choice in
        yes|y)
            echo "Remove: ${HELM_ARGS[0]}"
            helm uninstall "${HELM_ARGS[0]}" -n "${HELM_ARGS[5]}"
            #    --cascade foreground
            ;;
        *) echo "✓ Cancelled by user."
            exit 1
            ;;
    esac
}

### Main script logic
if [[ $# -eq 0 ]]; then
    usage
fi

COMMAND="$1"
case "${COMMAND}" in
    deploy)
        prep_req
        load_config "$@"
        diff
        deploy
        ;;
    diff)
        prep_req
        load_config "$@"
        diff
        ;;
    uninstall)
        prep_req
        load_config "$@"
        uninstall
        ;;
    help)
        usage
        ;;
    version)
        version
        ;;
    *)
        echo "Error: Unknown command '${COMMAND}'" >&2
        usage
        ;;
esac

